// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenVoting.Data;

#nullable disable

namespace OpenVoting.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260208021409_AddFieldRequirements")]
    partial class AddFieldRequirements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenVoting.Data.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Bytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("OpenVoting.Data.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalCommunityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "ExternalCommunityId")
                        .IsUnique();

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("OpenVoting.Data.CommunityMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("RoleIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId", "Platform", "ExternalUserId")
                        .IsUnique();

                    b.ToTable("CommunityMembers");
                });

            modelBuilder.Entity("OpenVoting.Data.Poll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DescriptionRequirement")
                        .HasColumnType("integer");

                    b.Property<bool>("HideEntriesUntilVoting")
                        .HasColumnType("boolean");

                    b.Property<int>("ImageRequirement")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxSelections")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSubmissionsPerMember")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("MustHaveJoinedBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RequireRanking")
                        .HasColumnType("boolean");

                    b.Property<string>("RequiredRoleIdsJson")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SubmissionClosesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("SubmissionOpensAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TitleRequirement")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("VotingClosesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VotingMethod")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("VotingOpensAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId", "Status");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("OpenVoting.Data.PollEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisqualificationReason")
                        .HasColumnType("text");

                    b.Property<bool>("IsDisqualified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OriginalAssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PublicAssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubmittedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeaserAssetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OriginalAssetId");

                    b.HasIndex("PollId");

                    b.HasIndex("PublicAssetId");

                    b.HasIndex("SubmittedByMemberId");

                    b.HasIndex("TeaserAssetId");

                    b.ToTable("PollEntries");
                });

            modelBuilder.Entity("OpenVoting.Data.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("PollId", "MemberId")
                        .IsUnique();

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("OpenVoting.Data.VoteChoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.Property<Guid>("VoteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("VoteId", "EntryId")
                        .IsUnique();

                    b.HasIndex("VoteId", "Rank");

                    b.ToTable("VoteChoices");
                });

            modelBuilder.Entity("OpenVoting.Data.CommunityMember", b =>
                {
                    b.HasOne("OpenVoting.Data.Community", "Community")
                        .WithMany("Members")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("OpenVoting.Data.Poll", b =>
                {
                    b.HasOne("OpenVoting.Data.Community", "Community")
                        .WithMany("Polls")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("OpenVoting.Data.PollEntry", b =>
                {
                    b.HasOne("OpenVoting.Data.Asset", "OriginalAsset")
                        .WithMany()
                        .HasForeignKey("OriginalAssetId");

                    b.HasOne("OpenVoting.Data.Poll", "Poll")
                        .WithMany("Entries")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenVoting.Data.Asset", "PublicAsset")
                        .WithMany()
                        .HasForeignKey("PublicAssetId");

                    b.HasOne("OpenVoting.Data.CommunityMember", "SubmittedByMember")
                        .WithMany("Entries")
                        .HasForeignKey("SubmittedByMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenVoting.Data.Asset", "TeaserAsset")
                        .WithMany()
                        .HasForeignKey("TeaserAssetId");

                    b.Navigation("OriginalAsset");

                    b.Navigation("Poll");

                    b.Navigation("PublicAsset");

                    b.Navigation("SubmittedByMember");

                    b.Navigation("TeaserAsset");
                });

            modelBuilder.Entity("OpenVoting.Data.Vote", b =>
                {
                    b.HasOne("OpenVoting.Data.CommunityMember", "Member")
                        .WithMany("Votes")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenVoting.Data.Poll", "Poll")
                        .WithMany("Votes")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("OpenVoting.Data.VoteChoice", b =>
                {
                    b.HasOne("OpenVoting.Data.PollEntry", "Entry")
                        .WithMany("VoteChoices")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenVoting.Data.Vote", "Vote")
                        .WithMany("Choices")
                        .HasForeignKey("VoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Vote");
                });

            modelBuilder.Entity("OpenVoting.Data.Community", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Polls");
                });

            modelBuilder.Entity("OpenVoting.Data.CommunityMember", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("OpenVoting.Data.Poll", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("OpenVoting.Data.PollEntry", b =>
                {
                    b.Navigation("VoteChoices");
                });

            modelBuilder.Entity("OpenVoting.Data.Vote", b =>
                {
                    b.Navigation("Choices");
                });
#pragma warning restore 612, 618
        }
    }
}
